// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: axiome/referral/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState - all referral state that must be provided at genesis
type GenesisState struct {
	Params           Params      `protobuf:"bytes,1,opt,name=params,proto3" json:"params" yaml:"params"`
	TopLevelAccounts []*RefInfo  `protobuf:"bytes,2,rep,name=top_level_accounts,json=topLevelAccounts,proto3" json:"top_level_accounts" yaml:"top_level_accounts"`
	OtherAccounts    []Refs      `protobuf:"bytes,3,rep,name=other_accounts,json=otherAccounts,proto3" json:"other_accounts" yaml:"other_accounts,omitempty"`
	Downgrades       []Downgrade `protobuf:"bytes,4,rep,name=downgrades,proto3" json:"downgrades" yaml:"downgrades,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_7327d38a9d008212, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

type Refs struct {
	Referrer  string     `protobuf:"bytes,1,opt,name=referrer,proto3" json:"referrer" yaml:"referrer"`
	Referrals []*RefInfo `protobuf:"bytes,2,rep,name=referrals,proto3" json:"referrals,omitempty" yaml:"referrals,omitempty"`
}

func (m *Refs) Reset()         { *m = Refs{} }
func (m *Refs) String() string { return proto.CompactTextString(m) }
func (*Refs) ProtoMessage()    {}
func (*Refs) Descriptor() ([]byte, []int) {
	return fileDescriptor_7327d38a9d008212, []int{1}
}
func (m *Refs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Refs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Refs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Refs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Refs.Merge(m, src)
}
func (m *Refs) XXX_Size() int {
	return m.Size()
}
func (m *Refs) XXX_DiscardUnknown() {
	xxx_messageInfo_Refs.DiscardUnknown(m)
}

var xxx_messageInfo_Refs proto.InternalMessageInfo

type RefInfo struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address" yaml:"address"`
	Status  Status `protobuf:"varint,2,opt,name=status,proto3,enum=axiome.referral.v1beta1.Status" json:"status" yaml:"status"`
}

func (m *RefInfo) Reset()         { *m = RefInfo{} }
func (m *RefInfo) String() string { return proto.CompactTextString(m) }
func (*RefInfo) ProtoMessage()    {}
func (*RefInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7327d38a9d008212, []int{2}
}
func (m *RefInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RefInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RefInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RefInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefInfo.Merge(m, src)
}
func (m *RefInfo) XXX_Size() int {
	return m.Size()
}
func (m *RefInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RefInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RefInfo proto.InternalMessageInfo

type Downgrade struct {
	Account string    `protobuf:"bytes,1,opt,name=account,proto3" json:"account" yaml:"account"`
	Current Status    `protobuf:"varint,2,opt,name=current,proto3,enum=axiome.referral.v1beta1.Status" json:"current" yaml:"current"`
	Time    time.Time `protobuf:"bytes,3,opt,name=time,proto3,stdtime" json:"time" yaml:"time"`
}

func (m *Downgrade) Reset()         { *m = Downgrade{} }
func (m *Downgrade) String() string { return proto.CompactTextString(m) }
func (*Downgrade) ProtoMessage()    {}
func (*Downgrade) Descriptor() ([]byte, []int) {
	return fileDescriptor_7327d38a9d008212, []int{3}
}
func (m *Downgrade) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Downgrade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Downgrade.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Downgrade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Downgrade.Merge(m, src)
}
func (m *Downgrade) XXX_Size() int {
	return m.Size()
}
func (m *Downgrade) XXX_DiscardUnknown() {
	xxx_messageInfo_Downgrade.DiscardUnknown(m)
}

var xxx_messageInfo_Downgrade proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GenesisState)(nil), "axiome.referral.v1beta1.GenesisState")
	proto.RegisterType((*Refs)(nil), "axiome.referral.v1beta1.Refs")
	proto.RegisterType((*RefInfo)(nil), "axiome.referral.v1beta1.RefInfo")
	proto.RegisterType((*Downgrade)(nil), "axiome.referral.v1beta1.Downgrade")
}

func init() {
	proto.RegisterFile("axiome/referral/v1beta1/genesis.proto", fileDescriptor_7327d38a9d008212)
}

var fileDescriptor_7327d38a9d008212 = []byte{
	// 616 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x41, 0x6f, 0xd3, 0x30,
	0x18, 0x6d, 0x68, 0xb5, 0x31, 0x97, 0x15, 0x14, 0x21, 0x51, 0x3a, 0x2d, 0xae, 0x3c, 0x10, 0x3d,
	0xb0, 0x44, 0xdb, 0x0e, 0x48, 0xe3, 0x44, 0x84, 0x84, 0x26, 0x21, 0x81, 0xb2, 0x1d, 0x26, 0x0e,
	0x4c, 0x6e, 0xeb, 0x66, 0x91, 0x92, 0x38, 0x72, 0xdc, 0xd1, 0x9e, 0xb9, 0x70, 0xdc, 0x2f, 0x40,
	0x5c, 0xf9, 0x27, 0x3b, 0x70, 0xd8, 0x91, 0x93, 0x41, 0xed, 0xad, 0xc7, 0x48, 0xdc, 0x51, 0x6c,
	0xa7, 0x69, 0x05, 0x9d, 0x76, 0xb3, 0xdf, 0xf7, 0xbe, 0xf7, 0x9e, 0x65, 0xfb, 0x03, 0x4f, 0xf1,
	0x28, 0xa0, 0x11, 0x71, 0x18, 0x19, 0x10, 0xc6, 0x70, 0xe8, 0x5c, 0xec, 0x75, 0x09, 0xc7, 0x7b,
	0x8e, 0x4f, 0x62, 0x92, 0x06, 0xa9, 0x9d, 0x30, 0xca, 0xa9, 0xf9, 0x48, 0xd1, 0xec, 0x82, 0x66,
	0x6b, 0x5a, 0xeb, 0xa1, 0x4f, 0x7d, 0x2a, 0x39, 0x4e, 0xbe, 0x52, 0xf4, 0x16, 0xf4, 0x29, 0xf5,
	0x43, 0xe2, 0xc8, 0x5d, 0x77, 0x38, 0x70, 0x78, 0x10, 0x91, 0x94, 0xe3, 0x28, 0xd1, 0x84, 0x27,
	0xab, 0x6c, 0x13, 0xcc, 0x70, 0xa4, 0x5d, 0x5b, 0x3b, 0xab, 0x58, 0x7c, 0x9c, 0x10, 0x4d, 0x42,
	0x3f, 0xaa, 0xe0, 0xde, 0x1b, 0x15, 0xf6, 0x98, 0x63, 0x4e, 0xcc, 0x53, 0xb0, 0xa6, 0x54, 0x9a,
	0x46, 0xdb, 0xe8, 0xd4, 0xf7, 0xa1, 0xbd, 0x22, 0xbc, 0xfd, 0x5e, 0xd2, 0x5c, 0x78, 0x25, 0x60,
	0x65, 0x26, 0xa0, 0x6e, 0xcb, 0x04, 0xdc, 0x1c, 0xe3, 0x28, 0x3c, 0x44, 0x6a, 0x8f, 0x3c, 0x5d,
	0x30, 0x3f, 0x1b, 0xc0, 0xe4, 0x34, 0x39, 0x0b, 0xc9, 0x05, 0x09, 0xcf, 0x70, 0xaf, 0x47, 0x87,
	0x31, 0x4f, 0x9b, 0x77, 0xda, 0xd5, 0x4e, 0x7d, 0xbf, 0xbd, 0xd2, 0xc6, 0x23, 0x83, 0xa3, 0x78,
	0x40, 0xdd, 0x83, 0x99, 0x80, 0xff, 0xe9, 0xcf, 0x04, 0x7c, 0xac, 0xfc, 0xfe, 0xad, 0x21, 0xef,
	0x01, 0xa7, 0xc9, 0xdb, 0x1c, 0x7b, 0xa5, 0x21, 0x33, 0x02, 0x0d, 0xca, 0xcf, 0x09, 0x2b, 0x03,
	0x54, 0x65, 0x80, 0xed, 0x9b, 0x02, 0xa4, 0xee, 0xb3, 0xfc, 0x94, 0x99, 0x80, 0x50, 0x79, 0x2d,
	0x4b, 0x3c, 0xa7, 0x51, 0xc0, 0x49, 0x94, 0xf0, 0x31, 0xf2, 0x36, 0x65, 0x69, 0x6e, 0xe7, 0x03,
	0xd0, 0xa7, 0x9f, 0x62, 0x9f, 0xe1, 0x3e, 0x49, 0x9b, 0x35, 0x69, 0x85, 0x56, 0x5a, 0xbd, 0x2e,
	0xa8, 0xee, 0x8e, 0xf6, 0xdb, 0x52, 0x7e, 0xa5, 0xc6, 0xa2, 0xd7, 0x82, 0xf4, 0x61, 0xed, 0xcb,
	0x37, 0x58, 0x41, 0xdf, 0x0d, 0x50, 0xcb, 0xf3, 0x9a, 0x2f, 0xc1, 0x5d, 0xa5, 0x4e, 0x98, 0xbc,
	0xc8, 0x0d, 0x17, 0xce, 0x04, 0x9c, 0x63, 0x99, 0x80, 0xf7, 0x95, 0x72, 0x81, 0x20, 0x6f, 0x5e,
	0x34, 0x3f, 0x82, 0x8d, 0x22, 0xda, 0xed, 0xef, 0xc7, 0xca, 0x04, 0x6c, 0x2d, 0x6a, 0xe2, 0x70,
	0x29, 0x6c, 0x29, 0xa9, 0xb3, 0x7e, 0x35, 0xc0, 0xba, 0x6e, 0x36, 0x5f, 0x80, 0x75, 0xdc, 0xef,
	0x33, 0x92, 0xa6, 0x3a, 0xed, 0xf6, 0x4c, 0xc0, 0x02, 0xca, 0x04, 0x6c, 0x28, 0x61, 0x0d, 0x20,
	0xaf, 0x28, 0x99, 0x27, 0x60, 0x2d, 0xe5, 0x98, 0x0f, 0xf3, 0x9c, 0x46, 0xa7, 0x71, 0xc3, 0x73,
	0x3d, 0x96, 0x34, 0x77, 0x2b, 0x7f, 0xaa, 0xaa, 0xa5, 0x7c, 0xaa, 0x6a, 0x8f, 0x3c, 0x5d, 0xd0,
	0x01, 0xff, 0x18, 0x60, 0x63, 0x7e, 0x23, 0x32, 0xa2, 0xba, 0xd5, 0xa5, 0x88, 0x0a, 0x5a, 0x88,
	0xa8, 0x80, 0x3c, 0xa2, 0x5a, 0x99, 0xa7, 0x60, 0xbd, 0x37, 0x64, 0x8c, 0xc4, 0xfc, 0xb6, 0x19,
	0xa5, 0xb2, 0xee, 0x29, 0x95, 0x35, 0x80, 0xbc, 0xa2, 0x64, 0xbe, 0x03, 0xb5, 0x7c, 0x34, 0x34,
	0xab, 0xf2, 0xa7, 0xb6, 0x6c, 0x35, 0x37, 0xec, 0x62, 0x6e, 0xd8, 0x27, 0xc5, 0xdc, 0x98, 0x7f,
	0x52, 0xc9, 0xcf, 0x04, 0xac, 0xeb, 0x2f, 0x13, 0x44, 0x04, 0x5d, 0xfe, 0x82, 0x86, 0x27, 0x0b,
	0xea, 0xdc, 0xee, 0xd1, 0xd5, 0xc4, 0x32, 0xae, 0x27, 0x96, 0xf1, 0x7b, 0x62, 0x19, 0x97, 0x53,
	0xab, 0x72, 0x3d, 0xb5, 0x2a, 0x3f, 0xa7, 0x56, 0xe5, 0x83, 0xe3, 0x07, 0xfc, 0x7c, 0xd8, 0xb5,
	0x7b, 0x34, 0x72, 0xd4, 0x19, 0x76, 0x13, 0x46, 0x1d, 0x3c, 0x8a, 0x76, 0x63, 0xda, 0x27, 0xce,
	0xa8, 0x1c, 0x36, 0x72, 0xc8, 0x74, 0xd7, 0x64, 0x96, 0x83, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x92, 0xe1, 0x9d, 0xfe, 0x29, 0x05, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Downgrades) > 0 {
		for iNdEx := len(m.Downgrades) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Downgrades[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.OtherAccounts) > 0 {
		for iNdEx := len(m.OtherAccounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OtherAccounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.TopLevelAccounts) > 0 {
		for iNdEx := len(m.TopLevelAccounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TopLevelAccounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Refs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Refs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Refs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Referrals) > 0 {
		for iNdEx := len(m.Referrals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Referrals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Referrer) > 0 {
		i -= len(m.Referrer)
		copy(dAtA[i:], m.Referrer)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Referrer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RefInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RefInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RefInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Downgrade) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Downgrade) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Downgrade) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.Time, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Time):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintGenesis(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x1a
	if m.Current != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Current))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.TopLevelAccounts) > 0 {
		for _, e := range m.TopLevelAccounts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.OtherAccounts) > 0 {
		for _, e := range m.OtherAccounts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Downgrades) > 0 {
		for _, e := range m.Downgrades {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *Refs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Referrer)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.Referrals) > 0 {
		for _, e := range m.Referrals {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *RefInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovGenesis(uint64(m.Status))
	}
	return n
}

func (m *Downgrade) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Current != 0 {
		n += 1 + sovGenesis(uint64(m.Current))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Time)
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TopLevelAccounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TopLevelAccounts = append(m.TopLevelAccounts, &RefInfo{})
			if err := m.TopLevelAccounts[len(m.TopLevelAccounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OtherAccounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OtherAccounts = append(m.OtherAccounts, Refs{})
			if err := m.OtherAccounts[len(m.OtherAccounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Downgrades", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Downgrades = append(m.Downgrades, Downgrade{})
			if err := m.Downgrades[len(m.Downgrades)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Refs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Refs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Refs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Referrer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Referrer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Referrals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Referrals = append(m.Referrals, &RefInfo{})
			if err := m.Referrals[len(m.Referrals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RefInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RefInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RefInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Downgrade) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Downgrade: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Downgrade: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Current", wireType)
			}
			m.Current = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Current |= Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.Time, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
