// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: axiome/referral/v1beta1/params.proto

package types

import (
	fmt "fmt"
	github_com_axiome_pro_axm_node_util "github.com/axiome-pro/axm-node/util"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params - used for initializing default parameter for x/referral at genesis
type Params struct {
	DelegatingAward       NetworkAward `protobuf:"bytes,1,opt,name=delegating_award,json=delegatingAward,proto3" json:"delegating_award" yaml:"delegating_award"`
	StatusDowngradePeriod int32        `protobuf:"varint,2,opt,name=status_downgrade_period,json=statusDowngradePeriod,proto3" json:"status_downgrade_period,omitempty"`
	// uret_mode enables referral payouts in uret token instead of uaxm
	UretMode bool `protobuf:"varint,3,opt,name=uret_mode,json=uretMode,proto3" json:"uret_mode" yaml:"uret_mode"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d2d5cb0d9eee66, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetDelegatingAward() NetworkAward {
	if m != nil {
		return m.DelegatingAward
	}
	return NetworkAward{}
}

func (m *Params) GetStatusDowngradePeriod() int32 {
	if m != nil {
		return m.StatusDowngradePeriod
	}
	return 0
}

func (m *Params) GetUretMode() bool {
	if m != nil {
		return m.UretMode
	}
	return false
}

type NetworkAward struct {
	Network []github_com_axiome_pro_axm_node_util.Fraction `protobuf:"bytes,1,rep,name=network,proto3,customtype=github.com/axiome-pro/axm-node/util.Fraction" json:"network" yaml:"network,flow"`
}

func (m *NetworkAward) Reset()         { *m = NetworkAward{} }
func (m *NetworkAward) String() string { return proto.CompactTextString(m) }
func (*NetworkAward) ProtoMessage()    {}
func (*NetworkAward) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d2d5cb0d9eee66, []int{1}
}
func (m *NetworkAward) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NetworkAward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NetworkAward.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NetworkAward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkAward.Merge(m, src)
}
func (m *NetworkAward) XXX_Size() int {
	return m.Size()
}
func (m *NetworkAward) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkAward.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkAward proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "axiome.referral.v1beta1.Params")
	proto.RegisterType((*NetworkAward)(nil), "axiome.referral.v1beta1.NetworkAward")
}

func init() {
	proto.RegisterFile("axiome/referral/v1beta1/params.proto", fileDescriptor_c2d2d5cb0d9eee66)
}

var fileDescriptor_c2d2d5cb0d9eee66 = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xb1, 0xcb, 0xd3, 0x40,
	0x18, 0xc6, 0x73, 0x6d, 0xad, 0x6d, 0x14, 0x2c, 0x51, 0x69, 0x70, 0xc8, 0xc5, 0xa0, 0x90, 0xa1,
	0xcd, 0x51, 0x0b, 0x0e, 0x1d, 0x04, 0x83, 0x08, 0x0e, 0x4a, 0xc9, 0xe8, 0x12, 0xae, 0xbd, 0x6b,
	0x0c, 0x26, 0xb9, 0x70, 0xb9, 0x98, 0x76, 0x15, 0x5c, 0xc5, 0xd1, 0xb1, 0x7f, 0x4e, 0xc7, 0x8e,
	0xe2, 0x70, 0x48, 0xbb, 0x48, 0xc7, 0xfe, 0x05, 0xd2, 0xa4, 0xb1, 0xe2, 0xc7, 0xc7, 0xb7, 0xbd,
	0xf7, 0x3c, 0xbf, 0x7b, 0xee, 0xbd, 0xbb, 0x57, 0x7d, 0x82, 0x97, 0x21, 0x8b, 0x29, 0xe2, 0x74,
	0x41, 0x39, 0xc7, 0x11, 0xfa, 0x34, 0x9a, 0x51, 0x81, 0x47, 0x28, 0xc5, 0x1c, 0xc7, 0x99, 0x93,
	0x72, 0x26, 0x98, 0xd6, 0xaf, 0x28, 0xa7, 0xa6, 0x9c, 0x33, 0xf5, 0xe8, 0x41, 0xc0, 0x02, 0x56,
	0x32, 0xe8, 0x54, 0x55, 0xb8, 0xf5, 0xb5, 0xa1, 0xb6, 0xa7, 0xe5, 0x7e, 0xed, 0x0b, 0x50, 0x7b,
	0x84, 0x46, 0x34, 0xc0, 0x22, 0x4c, 0x02, 0x1f, 0x17, 0x98, 0x13, 0x1d, 0x98, 0xc0, 0xbe, 0xf3,
	0xec, 0xa9, 0x73, 0x4d, 0xaa, 0xf3, 0x8e, 0x8a, 0x82, 0xf1, 0x8f, 0x2f, 0x4f, 0xb0, 0x3b, 0xde,
	0x48, 0xa8, 0x1c, 0x24, 0xbc, 0x12, 0x73, 0x94, 0xb0, 0xbf, 0xc2, 0x71, 0x34, 0xb1, 0xfe, 0x77,
	0x2c, 0xef, 0xde, 0x45, 0x2a, 0x53, 0xb4, 0xe7, 0x6a, 0x3f, 0x13, 0x58, 0xe4, 0x99, 0x4f, 0x58,
	0x91, 0x04, 0x1c, 0x13, 0xea, 0xa7, 0x94, 0x87, 0x8c, 0xe8, 0x0d, 0x13, 0xd8, 0xb7, 0xbc, 0x87,
	0x95, 0xfd, 0xaa, 0x76, 0xa7, 0xa5, 0xa9, 0xbd, 0x50, 0xbb, 0x39, 0xa7, 0xc2, 0x8f, 0x19, 0xa1,
	0x7a, 0xd3, 0x04, 0x76, 0xc7, 0x7d, 0x7c, 0x90, 0xf0, 0x22, 0x1e, 0x25, 0xec, 0x55, 0x5d, 0xfc,
	0x95, 0x2c, 0xaf, 0x73, 0xaa, 0xdf, 0x32, 0x42, 0x27, 0xad, 0xef, 0x6b, 0xa8, 0x58, 0x9f, 0x81,
	0x7a, 0xf7, 0xdf, 0x4b, 0x69, 0x91, 0x7a, 0x3b, 0xa9, 0xd6, 0x3a, 0x30, 0x9b, 0x76, 0xd7, 0xf5,
	0x7e, 0x4a, 0x38, 0x08, 0x42, 0xf1, 0x21, 0x9f, 0x39, 0x73, 0x16, 0xa3, 0xea, 0x69, 0x86, 0x29,
	0x67, 0x08, 0x2f, 0xe3, 0x61, 0xc2, 0x08, 0x45, 0xb9, 0x08, 0x23, 0xe7, 0x35, 0xc7, 0x73, 0x11,
	0xb2, 0xe4, 0x20, 0x61, 0x1d, 0x71, 0x94, 0xf0, 0x7e, 0xd5, 0xc2, 0x59, 0x18, 0x2c, 0x22, 0x56,
	0x58, 0x5e, 0xed, 0x4f, 0x5a, 0xbf, 0xd7, 0x10, 0xb8, 0x6f, 0x36, 0x3b, 0x03, 0x6c, 0x77, 0x06,
	0xf8, 0xb5, 0x33, 0xc0, 0xb7, 0xbd, 0xa1, 0x6c, 0xf7, 0x86, 0xf2, 0x63, 0x6f, 0x28, 0xef, 0xd1,
	0x0d, 0x07, 0x2f, 0x2f, 0xe3, 0x21, 0x56, 0x29, 0xcd, 0x66, 0xed, 0xf2, 0x9f, 0xc7, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x4d, 0x31, 0xfb, 0x94, 0x3e, 0x02, 0x00, 0x00,
}

func (this *NetworkAward) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*NetworkAward)
	if !ok {
		that2, ok := that.(NetworkAward)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Network) != len(that1.Network) {
		return false
	}
	for i := range this.Network {
		if !this.Network[i].Equal(that1.Network[i]) {
			return false
		}
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UretMode {
		i--
		if m.UretMode {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.StatusDowngradePeriod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.StatusDowngradePeriod))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.DelegatingAward.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *NetworkAward) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NetworkAward) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NetworkAward) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Network) > 0 {
		for iNdEx := len(m.Network) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.Network[iNdEx].Size()
				i -= size
				if _, err := m.Network[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.DelegatingAward.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.StatusDowngradePeriod != 0 {
		n += 1 + sovParams(uint64(m.StatusDowngradePeriod))
	}
	if m.UretMode {
		n += 2
	}
	return n
}

func (m *NetworkAward) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Network) > 0 {
		for _, e := range m.Network {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegatingAward", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DelegatingAward.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusDowngradePeriod", wireType)
			}
			m.StatusDowngradePeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StatusDowngradePeriod |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UretMode", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.UretMode = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NetworkAward) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NetworkAward: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NetworkAward: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Network", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_axiome_pro_axm_node_util.Fraction
			m.Network = append(m.Network, v)
			if err := m.Network[len(m.Network)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
