// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: axiome/referral/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgRegisterReferral place referral to it's referrer
// in Referral marketing module
type MsgRegisterReferral struct {
	ReferralAddress string `protobuf:"bytes,1,opt,name=referral_address,json=referralAddress,proto3" json:"referral_address,omitempty"`
	ReferrerAddress string `protobuf:"bytes,2,opt,name=referrer_address,json=referrerAddress,proto3" json:"referrer_address,omitempty"`
}

func (m *MsgRegisterReferral) Reset()         { *m = MsgRegisterReferral{} }
func (m *MsgRegisterReferral) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterReferral) ProtoMessage()    {}
func (*MsgRegisterReferral) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0aa3dc3a0edc55d, []int{0}
}
func (m *MsgRegisterReferral) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterReferral) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterReferral.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterReferral) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterReferral.Merge(m, src)
}
func (m *MsgRegisterReferral) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterReferral) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterReferral.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterReferral proto.InternalMessageInfo

// MsgRegisterReferralResponse defines the Msg/RegisterReferral response
// type.
type MsgRegisterReferralResponse struct {
}

func (m *MsgRegisterReferralResponse) Reset()         { *m = MsgRegisterReferralResponse{} }
func (m *MsgRegisterReferralResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterReferralResponse) ProtoMessage()    {}
func (*MsgRegisterReferralResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0aa3dc3a0edc55d, []int{1}
}
func (m *MsgRegisterReferralResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterReferralResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterReferralResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterReferralResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterReferralResponse.Merge(m, src)
}
func (m *MsgRegisterReferralResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterReferralResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterReferralResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterReferralResponse proto.InternalMessageInfo

type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless
	// overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params    Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0aa3dc3a0edc55d, []int{2}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0aa3dc3a0edc55d, []int{3}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgBurnPartnerFee is a message to burn coins on sender's account, meanwhile
// for burning partner fees or etc.
type MsgBurnPartnerFee struct {
	// Account is a sender's SDK address.
	FromAddress string                                   `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	Amount      github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
}

func (m *MsgBurnPartnerFee) Reset()         { *m = MsgBurnPartnerFee{} }
func (m *MsgBurnPartnerFee) String() string { return proto.CompactTextString(m) }
func (*MsgBurnPartnerFee) ProtoMessage()    {}
func (*MsgBurnPartnerFee) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0aa3dc3a0edc55d, []int{4}
}
func (m *MsgBurnPartnerFee) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBurnPartnerFee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBurnPartnerFee.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBurnPartnerFee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBurnPartnerFee.Merge(m, src)
}
func (m *MsgBurnPartnerFee) XXX_Size() int {
	return m.Size()
}
func (m *MsgBurnPartnerFee) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBurnPartnerFee.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBurnPartnerFee proto.InternalMessageInfo

// MsgBurnPartnerFeeResponse defines response type for MsgBurnPartnerFee
// messages.
type MsgBurnPartnerFeeResponse struct {
}

func (m *MsgBurnPartnerFeeResponse) Reset()         { *m = MsgBurnPartnerFeeResponse{} }
func (m *MsgBurnPartnerFeeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBurnPartnerFeeResponse) ProtoMessage()    {}
func (*MsgBurnPartnerFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0aa3dc3a0edc55d, []int{5}
}
func (m *MsgBurnPartnerFeeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBurnPartnerFeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBurnPartnerFeeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBurnPartnerFeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBurnPartnerFeeResponse.Merge(m, src)
}
func (m *MsgBurnPartnerFeeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBurnPartnerFeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBurnPartnerFeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBurnPartnerFeeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterReferral)(nil), "axiome.referral.v1beta1.MsgRegisterReferral")
	proto.RegisterType((*MsgRegisterReferralResponse)(nil), "axiome.referral.v1beta1.MsgRegisterReferralResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "axiome.referral.v1beta1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "axiome.referral.v1beta1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgBurnPartnerFee)(nil), "axiome.referral.v1beta1.MsgBurnPartnerFee")
	proto.RegisterType((*MsgBurnPartnerFeeResponse)(nil), "axiome.referral.v1beta1.MsgBurnPartnerFeeResponse")
}

func init() { proto.RegisterFile("axiome/referral/v1beta1/tx.proto", fileDescriptor_d0aa3dc3a0edc55d) }

var fileDescriptor_d0aa3dc3a0edc55d = []byte{
	// 599 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x3d, 0x6f, 0xd3, 0x40,
	0x18, 0xb6, 0x5b, 0x51, 0x29, 0x97, 0x88, 0xb6, 0xa6, 0x52, 0x12, 0x57, 0xd8, 0x51, 0xc4, 0x10,
	0x45, 0xc4, 0x47, 0x02, 0x62, 0x08, 0x2c, 0xb8, 0x52, 0x25, 0x86, 0x48, 0x55, 0x10, 0x0b, 0x4b,
	0x74, 0x49, 0xae, 0x57, 0x43, 0xed, 0xb3, 0xee, 0x2e, 0x51, 0xb2, 0x21, 0x26, 0xc4, 0xc4, 0xcc,
	0xd4, 0x11, 0x31, 0x65, 0xe0, 0x0f, 0xb0, 0x75, 0xac, 0x98, 0x58, 0xf8, 0x50, 0x22, 0x11, 0x7e,
	0x06, 0xb2, 0x7d, 0xce, 0x77, 0x4a, 0x58, 0xe2, 0xf8, 0x7d, 0x9f, 0xf7, 0xe3, 0x79, 0x9f, 0x47,
	0x06, 0x39, 0xd4, 0x73, 0xa8, 0x8b, 0x21, 0xc3, 0xa7, 0x98, 0x31, 0x74, 0x0e, 0xbb, 0xe5, 0x26,
	0x16, 0xa8, 0x0c, 0x45, 0xcf, 0xf2, 0x19, 0x15, 0x54, 0x4b, 0x47, 0x08, 0x2b, 0x46, 0x58, 0x12,
	0xa1, 0x1f, 0x10, 0x4a, 0x68, 0x88, 0x81, 0xc1, 0xbf, 0x08, 0xae, 0x67, 0x5b, 0x94, 0xbb, 0x94,
	0x37, 0xa2, 0x44, 0xf4, 0x22, 0x53, 0xe9, 0xe8, 0x0d, 0xba, 0x9c, 0xc0, 0x6e, 0x39, 0x78, 0xc8,
	0x84, 0x21, 0x13, 0x4d, 0xc4, 0xf1, 0x64, 0x81, 0x16, 0x75, 0x3c, 0x99, 0xdf, 0x47, 0xae, 0xe3,
	0x51, 0x18, 0xfe, 0xca, 0xd0, 0x9d, 0x75, 0x7b, 0xfb, 0x88, 0x21, 0x57, 0x4e, 0xcc, 0x7f, 0x57,
	0xc1, 0xad, 0x1a, 0x27, 0x75, 0x4c, 0x1c, 0x2e, 0x30, 0xab, 0x4b, 0xb0, 0x76, 0x04, 0xf6, 0xe2,
	0xc2, 0x06, 0x6a, 0xb7, 0x19, 0xe6, 0x3c, 0xa3, 0xe6, 0xd4, 0x42, 0xc2, 0xce, 0x7c, 0xfd, 0x5c,
	0x3a, 0x90, 0x5b, 0x3f, 0x89, 0x32, 0xcf, 0x04, 0x73, 0x3c, 0x52, 0xdf, 0x8d, 0x2b, 0x64, 0x78,
	0xda, 0x04, 0xb3, 0x49, 0x93, 0xad, 0xcd, 0x9a, 0x60, 0x26, 0xc3, 0xd5, 0xc7, 0x6f, 0x2f, 0x4c,
	0xe5, 0xcf, 0x85, 0xa9, 0xbc, 0x19, 0x0f, 0x8a, 0x4b, 0x4b, 0xbd, 0x1b, 0x0f, 0x8a, 0xba, 0x64,
	0xba, 0x82, 0x47, 0xfe, 0x36, 0x38, 0x5c, 0x11, 0xae, 0x63, 0xee, 0x53, 0x8f, 0xe3, 0xfc, 0x17,
	0x15, 0xec, 0xd6, 0x38, 0x79, 0xee, 0xb7, 0x91, 0xc0, 0x27, 0xe1, 0x61, 0xb4, 0x87, 0x20, 0x81,
	0x3a, 0xe2, 0x8c, 0x32, 0x47, 0xf4, 0xff, 0xc9, 0x79, 0x0a, 0xd5, 0x6c, 0xb0, 0x13, 0x9d, 0x36,
	0xe4, 0x98, 0xac, 0x98, 0xd6, 0x1a, 0x5f, 0x58, 0xd1, 0x20, 0x3b, 0x71, 0xf9, 0xc3, 0x54, 0x3e,
	0x8e, 0x07, 0x45, 0xb5, 0x2e, 0x2b, 0xab, 0x95, 0x80, 0xe4, 0xb4, 0x67, 0xc0, 0xce, 0x5c, 0xd4,
	0x71, 0x61, 0xdf, 0x7c, 0x16, 0xa4, 0x17, 0x42, 0x13, 0x7a, 0xbf, 0x55, 0xb0, 0x5f, 0xe3, 0xc4,
	0xee, 0x30, 0xef, 0x04, 0x31, 0xe1, 0x61, 0x76, 0x8c, 0xb1, 0xf6, 0x08, 0xa4, 0x4e, 0x19, 0x75,
	0x37, 0xd6, 0x35, 0x19, 0xa0, 0x63, 0x4d, 0xfb, 0x60, 0x07, 0xb9, 0xb4, 0xe3, 0x89, 0xcc, 0x76,
	0x6e, 0xbb, 0x90, 0xac, 0x64, 0x2d, 0x59, 0x13, 0x58, 0x73, 0xc2, 0xf0, 0x88, 0x3a, 0x9e, 0x7d,
	0x1c, 0xf0, 0xfb, 0xf4, 0xd3, 0x2c, 0x10, 0x47, 0x9c, 0x75, 0x9a, 0x56, 0x8b, 0xba, 0xd2, 0xee,
	0xf2, 0x51, 0xe2, 0xed, 0x57, 0x50, 0xf4, 0x7d, 0xcc, 0xc3, 0x02, 0xfe, 0x61, 0x3c, 0x28, 0xa6,
	0xce, 0x31, 0x41, 0xad, 0x7e, 0x23, 0x30, 0x37, 0x97, 0xc7, 0x89, 0x06, 0x56, 0xb3, 0xb3, 0x4e,
	0x98, 0xa3, 0x90, 0x3f, 0x04, 0xd9, 0x25, 0x9e, 0xf1, 0x15, 0x2a, 0xc3, 0x2d, 0xb0, 0x5d, 0xe3,
	0x44, 0xeb, 0x82, 0xbd, 0x25, 0x9f, 0xdf, 0x5d, 0x2b, 0xd2, 0x0a, 0xdb, 0xe8, 0x0f, 0xfe, 0x07,
	0x1d, 0xcf, 0xd7, 0x5e, 0x82, 0xd4, 0x9c, 0xc1, 0x0a, 0xd7, 0x75, 0x99, 0x45, 0xea, 0xf7, 0x36,
	0x45, 0x4e, 0x66, 0xf9, 0xe0, 0xe6, 0x82, 0xda, 0xc5, 0xeb, 0x7a, 0xcc, 0x63, 0xf5, 0xca, 0xe6,
	0xd8, 0x78, 0xa2, 0x7e, 0xe3, 0x75, 0x20, 0x92, 0xfd, 0xf4, 0x72, 0x68, 0xa8, 0x57, 0x43, 0x43,
	0xfd, 0x35, 0x34, 0xd4, 0xf7, 0x23, 0x43, 0xb9, 0x1a, 0x19, 0xca, 0xb7, 0x91, 0xa1, 0xbc, 0x80,
	0x33, 0xf2, 0x47, 0xed, 0x4b, 0x3e, 0xa3, 0x10, 0xf5, 0xdc, 0x92, 0x47, 0xdb, 0x18, 0xf6, 0xa6,
	0xd6, 0x0e, 0xbd, 0xd0, 0xdc, 0x09, 0x3f, 0x4d, 0xf7, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xb9,
	0xb7, 0xed, 0xe9, 0x7a, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	RegisterReferral(ctx context.Context, in *MsgRegisterReferral, opts ...grpc.CallOption) (*MsgRegisterReferralResponse, error)
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	BurnPartnerFee(ctx context.Context, in *MsgBurnPartnerFee, opts ...grpc.CallOption) (*MsgBurnPartnerFeeResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterReferral(ctx context.Context, in *MsgRegisterReferral, opts ...grpc.CallOption) (*MsgRegisterReferralResponse, error) {
	out := new(MsgRegisterReferralResponse)
	err := c.cc.Invoke(ctx, "/axiome.referral.v1beta1.Msg/RegisterReferral", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/axiome.referral.v1beta1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BurnPartnerFee(ctx context.Context, in *MsgBurnPartnerFee, opts ...grpc.CallOption) (*MsgBurnPartnerFeeResponse, error) {
	out := new(MsgBurnPartnerFeeResponse)
	err := c.cc.Invoke(ctx, "/axiome.referral.v1beta1.Msg/BurnPartnerFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	RegisterReferral(context.Context, *MsgRegisterReferral) (*MsgRegisterReferralResponse, error)
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	BurnPartnerFee(context.Context, *MsgBurnPartnerFee) (*MsgBurnPartnerFeeResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterReferral(ctx context.Context, req *MsgRegisterReferral) (*MsgRegisterReferralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterReferral not implemented")
}
func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) BurnPartnerFee(ctx context.Context, req *MsgBurnPartnerFee) (*MsgBurnPartnerFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BurnPartnerFee not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterReferral_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterReferral)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterReferral(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axiome.referral.v1beta1.Msg/RegisterReferral",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterReferral(ctx, req.(*MsgRegisterReferral))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axiome.referral.v1beta1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BurnPartnerFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBurnPartnerFee)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BurnPartnerFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axiome.referral.v1beta1.Msg/BurnPartnerFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BurnPartnerFee(ctx, req.(*MsgBurnPartnerFee))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "axiome.referral.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterReferral",
			Handler:    _Msg_RegisterReferral_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "BurnPartnerFee",
			Handler:    _Msg_BurnPartnerFee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "axiome/referral/v1beta1/tx.proto",
}

func (m *MsgRegisterReferral) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterReferral) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterReferral) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ReferrerAddress) > 0 {
		i -= len(m.ReferrerAddress)
		copy(dAtA[i:], m.ReferrerAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ReferrerAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ReferralAddress) > 0 {
		i -= len(m.ReferralAddress)
		copy(dAtA[i:], m.ReferralAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ReferralAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterReferralResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterReferralResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterReferralResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgBurnPartnerFee) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBurnPartnerFee) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBurnPartnerFee) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBurnPartnerFeeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBurnPartnerFeeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBurnPartnerFeeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterReferral) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ReferralAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ReferrerAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterReferralResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgBurnPartnerFee) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgBurnPartnerFeeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterReferral) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterReferral: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterReferral: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReferralAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReferralAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReferrerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReferrerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterReferralResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterReferralResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterReferralResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBurnPartnerFee) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBurnPartnerFee: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBurnPartnerFee: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBurnPartnerFeeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBurnPartnerFeeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBurnPartnerFeeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
