// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: axiome/referral/v1beta1/types.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	STATUS_UNSPECIFIED Status = 0
	STATUS_NEW         Status = 1
	STATUS_STARTER     Status = 2
	STATUS_LEADER      Status = 3
	STATUS_GURU        Status = 4
	STATUS_BOSS        Status = 5
	STATUS_PRO         Status = 6
	STATUS_TOP         Status = 7
	STATUS_MEGA        Status = 8
	STATUS_DEPRECATED  Status = 9
)

var Status_name = map[int32]string{
	0: "STATUS_UNSPECIFIED",
	1: "STATUS_NEW",
	2: "STATUS_STARTER",
	3: "STATUS_LEADER",
	4: "STATUS_GURU",
	5: "STATUS_BOSS",
	6: "STATUS_PRO",
	7: "STATUS_TOP",
	8: "STATUS_MEGA",
	9: "STATUS_DEPRECATED",
}

var Status_value = map[string]int32{
	"STATUS_UNSPECIFIED": 0,
	"STATUS_NEW":         1,
	"STATUS_STARTER":     2,
	"STATUS_LEADER":      3,
	"STATUS_GURU":        4,
	"STATUS_BOSS":        5,
	"STATUS_PRO":         6,
	"STATUS_TOP":         7,
	"STATUS_MEGA":        8,
	"STATUS_DEPRECATED":  9,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_76735118a06b119c, []int{0}
}

type StatusCheckResult_Criterion_Rule int32

const (
	RULE_UNSPECIFIED                       StatusCheckResult_Criterion_Rule = 0
	RULE_N_REFERRALS_WITH_X_REFERRALS_EACH StatusCheckResult_Criterion_Rule = 1
	RULE_N_COINS_IN_STRUCTURE              StatusCheckResult_Criterion_Rule = 2
	RULE_N_TEAMS_OF_X_PEOPLE_EACH          StatusCheckResult_Criterion_Rule = 3
	RULE_PARTICIPATE_IN_REFERRAL_PROGRAM   StatusCheckResult_Criterion_Rule = 4
	RULE_SELF_STAKE                        StatusCheckResult_Criterion_Rule = 5
)

var StatusCheckResult_Criterion_Rule_name = map[int32]string{
	0: "RULE_UNSPECIFIED",
	1: "RULE_N_REFERRALS_WITH_X_REFERRALS_EACH",
	2: "RULE_N_COINS_IN_STRUCTURE",
	3: "RULE_N_TEAMS_OF_X_PEOPLE_EACH",
	4: "RULE_PARTICIPATE_IN_REFERRAL_PROGRAM",
	5: "RULE_SELF_STAKE",
}

var StatusCheckResult_Criterion_Rule_value = map[string]int32{
	"RULE_UNSPECIFIED":                       0,
	"RULE_N_REFERRALS_WITH_X_REFERRALS_EACH": 1,
	"RULE_N_COINS_IN_STRUCTURE":              2,
	"RULE_N_TEAMS_OF_X_PEOPLE_EACH":          3,
	"RULE_PARTICIPATE_IN_REFERRAL_PROGRAM":   4,
	"RULE_SELF_STAKE":                        5,
}

func (x StatusCheckResult_Criterion_Rule) String() string {
	return proto.EnumName(StatusCheckResult_Criterion_Rule_name, int32(x))
}

func (StatusCheckResult_Criterion_Rule) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_76735118a06b119c, []int{2, 0, 0}
}

type Info struct {
	// Status - account status
	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=axiome.referral.v1beta1.Status" json:"status" yaml:"status"`
	// Referrer - parent, account just above this one.
	Referrer string `protobuf:"bytes,2,opt,name=referrer,proto3" json:"referrer,omitempty" yaml:"referrer,omitempty"`
	// Active - does the account keeper have a paid subscription.
	Active bool `protobuf:"varint,4,opt,name=active,proto3" json:"active" yaml:"active"`
	// ActiveRefCounts - count of active referrals per level (up to 14 levels
	// deep). And so on. ActiveReferrals[0] represents an account itself. It must
	// be equal 1 if account is active, and 0 if it's not.
	ActiveRefCounts   []uint64               `protobuf:"varint,7,rep,packed,name=active_ref_counts,json=activeRefCounts,proto3" json:"active_ref_counts" yaml:"active_ref_counts,flow"`
	StatusDowngradeAt *time.Time             `protobuf:"bytes,8,opt,name=status_downgrade_at,json=statusDowngradeAt,proto3,stdtime" json:"status_downgrade_at,omitempty" yaml:"status_downgrade_at,omitempty"`
	SelfDelegated     *cosmossdk_io_math.Int `protobuf:"bytes,9,opt,name=self_delegated,json=selfDelegated,proto3,customtype=cosmossdk.io/math.Int" json:"delegated" yaml:"self_delegated,flow"`
	TeamDelegated     *cosmossdk_io_math.Int `protobuf:"bytes,10,opt,name=team_delegated,json=teamDelegated,proto3,customtype=cosmossdk.io/math.Int" json:"delegated" yaml:"team_delegated,flow"`
	ActiveCount       *ActiveAggregations    `protobuf:"bytes,11,opt,name=active_count,json=activeCount,proto3" json:"active_count,omitempty"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_76735118a06b119c, []int{0}
}
func (m *Info) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Info.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return m.Size()
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

type ActiveAggregations struct {
	FirstLine    int32 `protobuf:"varint,1,opt,name=first_line,json=firstLine,proto3" json:"first_line,omitempty"`
	FirstLineBy3 int32 `protobuf:"varint,2,opt,name=first_line_by3,json=firstLineBy3,proto3" json:"first_line_by3,omitempty"`
	Team0        int32 `protobuf:"varint,3,opt,name=team0,proto3" json:"team0,omitempty"`
	Team15       int32 `protobuf:"varint,4,opt,name=team15,proto3" json:"team15,omitempty"`
	Team50       int32 `protobuf:"varint,5,opt,name=team50,proto3" json:"team50,omitempty"`
	Team100      int32 `protobuf:"varint,6,opt,name=team100,proto3" json:"team100,omitempty"`
	Team300      int32 `protobuf:"varint,7,opt,name=team300,proto3" json:"team300,omitempty"`
}

func (m *ActiveAggregations) Reset()         { *m = ActiveAggregations{} }
func (m *ActiveAggregations) String() string { return proto.CompactTextString(m) }
func (*ActiveAggregations) ProtoMessage()    {}
func (*ActiveAggregations) Descriptor() ([]byte, []int) {
	return fileDescriptor_76735118a06b119c, []int{1}
}
func (m *ActiveAggregations) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActiveAggregations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActiveAggregations.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActiveAggregations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveAggregations.Merge(m, src)
}
func (m *ActiveAggregations) XXX_Size() int {
	return m.Size()
}
func (m *ActiveAggregations) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveAggregations.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveAggregations proto.InternalMessageInfo

type StatusCheckResult struct {
	Overall  bool                          `protobuf:"varint,1,opt,name=overall,proto3" json:"overall,omitempty"`
	Criteria []StatusCheckResult_Criterion `protobuf:"bytes,2,rep,name=criteria,proto3" json:"criteria"`
}

func (m *StatusCheckResult) Reset()         { *m = StatusCheckResult{} }
func (m *StatusCheckResult) String() string { return proto.CompactTextString(m) }
func (*StatusCheckResult) ProtoMessage()    {}
func (*StatusCheckResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_76735118a06b119c, []int{2}
}
func (m *StatusCheckResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StatusCheckResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StatusCheckResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StatusCheckResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusCheckResult.Merge(m, src)
}
func (m *StatusCheckResult) XXX_Size() int {
	return m.Size()
}
func (m *StatusCheckResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusCheckResult.DiscardUnknown(m)
}

var xxx_messageInfo_StatusCheckResult proto.InternalMessageInfo

type StatusCheckResult_Criterion struct {
	Met         bool                             `protobuf:"varint,1,opt,name=met,proto3" json:"met,omitempty"`
	Rule        StatusCheckResult_Criterion_Rule `protobuf:"varint,2,opt,name=rule,proto3,enum=axiome.referral.v1beta1.StatusCheckResult_Criterion_Rule" json:"rule,omitempty"`
	TargetValue uint64                           `protobuf:"varint,3,opt,name=target_value,json=targetValue,proto3" json:"target_value,omitempty"`
	ActualValue uint64                           `protobuf:"varint,4,opt,name=actual_value,json=actualValue,proto3" json:"actual_value,omitempty"`
	ParameterX  uint64                           `protobuf:"varint,5,opt,name=parameter_x,json=parameterX,proto3" json:"parameter_x,omitempty"`
}

func (m *StatusCheckResult_Criterion) Reset()         { *m = StatusCheckResult_Criterion{} }
func (m *StatusCheckResult_Criterion) String() string { return proto.CompactTextString(m) }
func (*StatusCheckResult_Criterion) ProtoMessage()    {}
func (*StatusCheckResult_Criterion) Descriptor() ([]byte, []int) {
	return fileDescriptor_76735118a06b119c, []int{2, 0}
}
func (m *StatusCheckResult_Criterion) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StatusCheckResult_Criterion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StatusCheckResult_Criterion.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StatusCheckResult_Criterion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusCheckResult_Criterion.Merge(m, src)
}
func (m *StatusCheckResult_Criterion) XXX_Size() int {
	return m.Size()
}
func (m *StatusCheckResult_Criterion) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusCheckResult_Criterion.DiscardUnknown(m)
}

var xxx_messageInfo_StatusCheckResult_Criterion proto.InternalMessageInfo

func (m *StatusCheckResult_Criterion) GetMet() bool {
	if m != nil {
		return m.Met
	}
	return false
}

func (m *StatusCheckResult_Criterion) GetRule() StatusCheckResult_Criterion_Rule {
	if m != nil {
		return m.Rule
	}
	return RULE_UNSPECIFIED
}

func (m *StatusCheckResult_Criterion) GetTargetValue() uint64 {
	if m != nil {
		return m.TargetValue
	}
	return 0
}

func (m *StatusCheckResult_Criterion) GetActualValue() uint64 {
	if m != nil {
		return m.ActualValue
	}
	return 0
}

func (m *StatusCheckResult_Criterion) GetParameterX() uint64 {
	if m != nil {
		return m.ParameterX
	}
	return 0
}

func init() {
	proto.RegisterEnum("axiome.referral.v1beta1.Status", Status_name, Status_value)
	proto.RegisterEnum("axiome.referral.v1beta1.StatusCheckResult_Criterion_Rule", StatusCheckResult_Criterion_Rule_name, StatusCheckResult_Criterion_Rule_value)
	proto.RegisterType((*Info)(nil), "axiome.referral.v1beta1.Info")
	proto.RegisterType((*ActiveAggregations)(nil), "axiome.referral.v1beta1.ActiveAggregations")
	proto.RegisterType((*StatusCheckResult)(nil), "axiome.referral.v1beta1.StatusCheckResult")
	proto.RegisterType((*StatusCheckResult_Criterion)(nil), "axiome.referral.v1beta1.StatusCheckResult.Criterion")
}

func init() {
	proto.RegisterFile("axiome/referral/v1beta1/types.proto", fileDescriptor_76735118a06b119c)
}

var fileDescriptor_76735118a06b119c = []byte{
	// 1089 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcf, 0x8f, 0xda, 0x46,
	0x14, 0xc6, 0x8b, 0x61, 0x61, 0x48, 0x88, 0x77, 0xf2, 0xa3, 0x0e, 0xd5, 0x62, 0x42, 0xa3, 0x0a,
	0xa5, 0x89, 0x21, 0x4b, 0x53, 0xa9, 0xb9, 0x19, 0xf0, 0x26, 0xa4, 0x2c, 0xd0, 0xb1, 0x49, 0xa2,
	0x5e, 0x2c, 0x03, 0x03, 0xb1, 0x62, 0x63, 0x64, 0x0f, 0x9b, 0xe5, 0x3f, 0xc8, 0x31, 0xc7, 0x5e,
	0x2a, 0xb5, 0xa9, 0xfa, 0x77, 0xf4, 0xd8, 0xdc, 0x9a, 0x63, 0xdb, 0x83, 0x5b, 0x25, 0xb7, 0x3d,
	0xee, 0x5f, 0x50, 0x79, 0xc6, 0x06, 0x36, 0xdb, 0x55, 0xa5, 0xdc, 0xe6, 0x7d, 0xdf, 0xf7, 0xbe,
	0xe7, 0xf7, 0xde, 0xd8, 0x06, 0x9f, 0x99, 0x47, 0x96, 0xeb, 0xe0, 0xaa, 0x87, 0x27, 0xd8, 0xf3,
	0x4c, 0xbb, 0x7a, 0x78, 0x77, 0x88, 0x89, 0x79, 0xb7, 0x4a, 0x96, 0x73, 0xec, 0xcb, 0x73, 0xcf,
	0x25, 0x2e, 0xfc, 0x84, 0x89, 0xe4, 0x58, 0x24, 0x47, 0xa2, 0xc2, 0x95, 0xa9, 0x3b, 0x75, 0xa9,
	0xa6, 0x1a, 0x9e, 0x98, 0xbc, 0x70, 0x7d, 0xea, 0xba, 0x53, 0x1b, 0x57, 0x69, 0x34, 0x5c, 0x4c,
	0xaa, 0xe6, 0x6c, 0x19, 0x51, 0xd2, 0x87, 0x14, 0xb1, 0x1c, 0xec, 0x13, 0xd3, 0x99, 0x33, 0x41,
	0xf9, 0x75, 0x1a, 0xf0, 0xed, 0xd9, 0xc4, 0x85, 0x3a, 0x48, 0xfb, 0xc4, 0x24, 0x0b, 0x5f, 0xe4,
	0x4a, 0x5c, 0x25, 0xbf, 0x27, 0xc9, 0xe7, 0x3c, 0x84, 0xac, 0x51, 0x59, 0xe3, 0xd3, 0xe3, 0x40,
	0x8a, 0x52, 0x4e, 0x02, 0xe9, 0xe2, 0xd2, 0x74, 0xec, 0xfb, 0x65, 0x16, 0x97, 0x51, 0x44, 0xc0,
	0x1e, 0xc8, 0xb0, 0x7c, 0xec, 0x89, 0x5b, 0x25, 0xae, 0x92, 0x6d, 0xd4, 0x8f, 0x03, 0x09, 0xc6,
	0xd8, 0x6d, 0xd7, 0xb1, 0x08, 0x76, 0xe6, 0x64, 0x79, 0x12, 0x48, 0xd7, 0x99, 0xc5, 0x59, 0xae,
	0x8c, 0x56, 0x26, 0xb0, 0x0e, 0xd2, 0xe6, 0x88, 0x58, 0x87, 0x58, 0xe4, 0x4b, 0x5c, 0x25, 0xc3,
	0x9e, 0x82, 0x21, 0xeb, 0xa7, 0x60, 0x71, 0x19, 0x45, 0x04, 0x1c, 0x82, 0x1d, 0x76, 0x32, 0x3c,
	0x3c, 0x31, 0x46, 0xee, 0x62, 0x46, 0x7c, 0x71, 0xbb, 0x94, 0xac, 0xf0, 0x8d, 0xaf, 0x8e, 0x03,
	0xe9, 0x2c, 0x79, 0x12, 0x48, 0xbb, 0x9b, 0x56, 0x1b, 0xd4, 0xed, 0x89, 0xed, 0xbe, 0x28, 0xa3,
	0x4b, 0x8c, 0x40, 0x78, 0xd2, 0xa4, 0x30, 0xfc, 0x81, 0x03, 0x97, 0x59, 0xd3, 0xc6, 0xd8, 0x7d,
	0x31, 0x9b, 0x7a, 0xe6, 0x18, 0x1b, 0x26, 0x11, 0x33, 0x25, 0xae, 0x92, 0xdb, 0x2b, 0xc8, 0x6c,
	0x11, 0x72, 0xbc, 0x08, 0x59, 0x8f, 0x17, 0xd1, 0xf8, 0xf6, 0x4d, 0x20, 0x71, 0xc7, 0x81, 0xb4,
	0xfb, 0x1f, 0xe9, 0xa7, 0x06, 0x74, 0x73, 0x73, 0xc6, 0xe7, 0xc8, 0xca, 0xaf, 0xfe, 0x96, 0x38,
	0xb4, 0xc3, 0x34, 0xad, 0x58, 0xa2, 0x10, 0xf8, 0x1c, 0xe4, 0x7d, 0x6c, 0x4f, 0x8c, 0x31, 0xb6,
	0xf1, 0xd4, 0x24, 0x78, 0x2c, 0x66, 0xe9, 0x3e, 0x5a, 0x7f, 0x05, 0xd2, 0xd5, 0x91, 0xeb, 0x3b,
	0xae, 0xef, 0x8f, 0x9f, 0xcb, 0x96, 0x5b, 0x75, 0x4c, 0xf2, 0x4c, 0x6e, 0xcf, 0xc8, 0x71, 0x20,
	0x65, 0x57, 0xea, 0x93, 0x40, 0x2a, 0x44, 0xe5, 0x4f, 0xb9, 0x44, 0xe3, 0xb8, 0x18, 0xa2, 0xad,
	0x18, 0x0c, 0x8b, 0x11, 0x6c, 0x3a, 0x1b, 0xc5, 0xc0, 0xc7, 0x15, 0x3b, 0xed, 0x12, 0x17, 0x0b,
	0xd1, 0x75, 0xb1, 0x2e, 0xb8, 0x10, 0x6d, 0x89, 0x6e, 0x48, 0xcc, 0xd1, 0x89, 0x7f, 0x71, 0xee,
	0xfd, 0x55, 0xa8, 0x58, 0x99, 0x4e, 0xbd, 0xd0, 0xc0, 0x72, 0x67, 0x3e, 0xca, 0x31, 0x03, 0xba,
	0xca, 0xfb, 0xfc, 0xcb, 0x1f, 0xa5, 0xc4, 0x23, 0x3e, 0x93, 0x12, 0xd2, 0x8f, 0xf8, 0x4c, 0x5a,
	0xd8, 0x2e, 0xff, 0xc9, 0x01, 0x78, 0x36, 0x0b, 0xee, 0x02, 0x30, 0xb1, 0x3c, 0x9f, 0x18, 0xb6,
	0x35, 0xc3, 0xf4, 0xb5, 0x49, 0xa1, 0x2c, 0x45, 0x3a, 0xd6, 0x0c, 0xc3, 0x9b, 0x20, 0xbf, 0xa6,
	0x8d, 0xe1, 0xb2, 0x4e, 0xdf, 0x80, 0x14, 0xba, 0xb0, 0x92, 0x34, 0x96, 0x75, 0x78, 0x05, 0xa4,
	0xc2, 0x76, 0x6a, 0x62, 0x92, 0x92, 0x2c, 0x80, 0xd7, 0x40, 0x3a, 0x3c, 0xdc, 0xbd, 0x47, 0xaf,
	0x79, 0x0a, 0x45, 0x51, 0x8c, 0xdf, 0xab, 0x89, 0xa9, 0x35, 0x7e, 0xaf, 0x06, 0x45, 0xb0, 0x4d,
	0x15, 0xb5, 0x9a, 0x98, 0xa6, 0x44, 0x1c, 0xc6, 0x4c, 0xbd, 0x56, 0x13, 0xb7, 0xd7, 0x4c, 0xbd,
	0x56, 0x63, 0x7d, 0x96, 0x7f, 0xe5, 0xc1, 0x0e, 0x7b, 0xa3, 0x9b, 0xcf, 0xf0, 0xe8, 0x39, 0xc2,
	0xfe, 0xc2, 0x26, 0x61, 0x96, 0x7b, 0x88, 0x3d, 0xd3, 0xb6, 0x69, 0x5f, 0x19, 0x14, 0x87, 0xf0,
	0x31, 0xc8, 0x8c, 0x3c, 0x8b, 0x60, 0xcf, 0x32, 0xc5, 0xad, 0x52, 0xb2, 0x92, 0xdb, 0xfb, 0xf2,
	0x7f, 0xbe, 0x14, 0x1b, 0xbe, 0x72, 0x93, 0xa5, 0xba, 0xb3, 0x06, 0xff, 0x26, 0x90, 0x12, 0x68,
	0xe5, 0x55, 0xf8, 0x25, 0x09, 0xb2, 0x2b, 0x16, 0x0a, 0x20, 0xe9, 0x60, 0x12, 0xd5, 0x0e, 0x8f,
	0xf0, 0x00, 0xf0, 0xde, 0xc2, 0xc6, 0x74, 0x86, 0xf9, 0xbd, 0xaf, 0x3f, 0xa6, 0xa6, 0x8c, 0x16,
	0x36, 0x46, 0xd4, 0x06, 0xde, 0x00, 0x17, 0x88, 0xe9, 0x4d, 0x31, 0x31, 0x0e, 0x4d, 0x7b, 0x81,
	0xe9, 0xf4, 0x79, 0x94, 0x63, 0xd8, 0xe3, 0x10, 0x0a, 0x25, 0xe6, 0x88, 0x2c, 0x4c, 0x3b, 0x92,
	0xf0, 0x4c, 0xc2, 0x30, 0x26, 0x91, 0x40, 0x6e, 0x6e, 0x7a, 0xa6, 0x83, 0x09, 0xf6, 0x8c, 0x23,
	0xba, 0x13, 0x1e, 0x81, 0x15, 0xf4, 0xb4, 0xfc, 0x3b, 0x07, 0xf8, 0xb0, 0x2a, 0xbc, 0x02, 0x04,
	0x34, 0xe8, 0xa8, 0xc6, 0xa0, 0xab, 0xf5, 0xd5, 0x66, 0x7b, 0xbf, 0xad, 0xb6, 0x84, 0x04, 0xbc,
	0x05, 0x3e, 0xa7, 0x68, 0xd7, 0x40, 0xea, 0xbe, 0x8a, 0x90, 0xd2, 0xd1, 0x8c, 0x27, 0x6d, 0xfd,
	0xa1, 0xf1, 0x74, 0x03, 0x50, 0x95, 0xe6, 0x43, 0x81, 0x83, 0xbb, 0xe0, 0x7a, 0xa4, 0x6d, 0xf6,
	0xda, 0x5d, 0xcd, 0x68, 0x77, 0x0d, 0x4d, 0x47, 0x83, 0xa6, 0x3e, 0x40, 0xaa, 0xb0, 0x05, 0x6f,
	0x80, 0xdd, 0x88, 0xd6, 0x55, 0xe5, 0x40, 0x33, 0x7a, 0xfb, 0xc6, 0x53, 0xa3, 0xaf, 0xf6, 0xfa,
	0x1d, 0x95, 0x39, 0x24, 0x61, 0x05, 0xdc, 0xa4, 0x92, 0xbe, 0x82, 0xf4, 0x76, 0xb3, 0xdd, 0x57,
	0x74, 0x35, 0x74, 0x89, 0x2b, 0x19, 0x7d, 0xd4, 0x7b, 0x80, 0x94, 0x03, 0x81, 0x87, 0x97, 0xc1,
	0x25, 0xaa, 0xd4, 0xd4, 0xce, 0xbe, 0xa1, 0xe9, 0xca, 0x37, 0xaa, 0x90, 0x2a, 0xf0, 0x2f, 0x7f,
	0x2e, 0x26, 0xee, 0x0b, 0xe1, 0xad, 0x79, 0xfb, 0x93, 0x94, 0x78, 0xf5, 0x5a, 0x4a, 0x7c, 0xff,
	0x5a, 0x4a, 0xdc, 0xfa, 0x8d, 0x03, 0x69, 0x36, 0x75, 0x78, 0x0d, 0x40, 0x4d, 0x57, 0xf4, 0x81,
	0xf6, 0x41, 0x9f, 0x79, 0x00, 0x22, 0xbc, 0xab, 0x3e, 0x11, 0x38, 0x08, 0x41, 0x3e, 0x8a, 0x35,
	0x5d, 0x41, 0xba, 0x8a, 0x84, 0x2d, 0xb8, 0x03, 0x2e, 0x46, 0x58, 0x47, 0x55, 0x5a, 0x2a, 0x12,
	0x92, 0xf0, 0x12, 0xc8, 0x45, 0xd0, 0x83, 0x01, 0x1a, 0x08, 0xfc, 0x06, 0xd0, 0xe8, 0x69, 0x9a,
	0x90, 0xda, 0x30, 0xee, 0xa3, 0x9e, 0x90, 0xde, 0x88, 0xf5, 0x5e, 0x5f, 0xd8, 0xde, 0x48, 0x38,
	0x50, 0x1f, 0x28, 0x42, 0x06, 0x5e, 0x05, 0x3b, 0x11, 0xd0, 0x52, 0xfb, 0x48, 0x6d, 0x2a, 0xba,
	0xda, 0x12, 0xb2, 0xac, 0xb7, 0x46, 0xfb, 0xcd, 0xbb, 0x22, 0xf7, 0xf6, 0x5d, 0x91, 0xfb, 0xe7,
	0x5d, 0x91, 0x7b, 0xf5, 0xbe, 0x98, 0x78, 0xfb, 0xbe, 0x98, 0xf8, 0xe3, 0x7d, 0x31, 0xf1, 0x5d,
	0x75, 0x6a, 0x91, 0x67, 0x8b, 0xa1, 0x3c, 0x72, 0x9d, 0x2a, 0xbb, 0x79, 0x77, 0xe6, 0x9e, 0x5b,
	0x35, 0x8f, 0x9c, 0x3b, 0x33, 0x77, 0x8c, 0xab, 0x47, 0xeb, 0x1f, 0x3a, 0xfd, 0x91, 0x0f, 0xd3,
	0xf4, 0x43, 0x5f, 0xff, 0x37, 0x00, 0x00, 0xff, 0xff, 0xca, 0x26, 0x62, 0x43, 0xf0, 0x07, 0x00,
	0x00,
}

func (m *Info) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Info) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Info) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ActiveCount != nil {
		{
			size, err := m.ActiveCount.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	if m.TeamDelegated != nil {
		{
			size := m.TeamDelegated.Size()
			i -= size
			if _, err := m.TeamDelegated.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x52
	}
	if m.SelfDelegated != nil {
		{
			size := m.SelfDelegated.Size()
			i -= size
			if _, err := m.SelfDelegated.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if m.StatusDowngradeAt != nil {
		n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.StatusDowngradeAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.StatusDowngradeAt):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintTypes(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x42
	}
	if len(m.ActiveRefCounts) > 0 {
		dAtA4 := make([]byte, len(m.ActiveRefCounts)*10)
		var j3 int
		for _, num := range m.ActiveRefCounts {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintTypes(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0x3a
	}
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.Referrer) > 0 {
		i -= len(m.Referrer)
		copy(dAtA[i:], m.Referrer)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Referrer)))
		i--
		dAtA[i] = 0x12
	}
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ActiveAggregations) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActiveAggregations) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActiveAggregations) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Team300 != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Team300))
		i--
		dAtA[i] = 0x38
	}
	if m.Team100 != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Team100))
		i--
		dAtA[i] = 0x30
	}
	if m.Team50 != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Team50))
		i--
		dAtA[i] = 0x28
	}
	if m.Team15 != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Team15))
		i--
		dAtA[i] = 0x20
	}
	if m.Team0 != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Team0))
		i--
		dAtA[i] = 0x18
	}
	if m.FirstLineBy3 != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.FirstLineBy3))
		i--
		dAtA[i] = 0x10
	}
	if m.FirstLine != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.FirstLine))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StatusCheckResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StatusCheckResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StatusCheckResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Criteria) > 0 {
		for iNdEx := len(m.Criteria) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Criteria[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Overall {
		i--
		if m.Overall {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StatusCheckResult_Criterion) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StatusCheckResult_Criterion) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StatusCheckResult_Criterion) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ParameterX != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ParameterX))
		i--
		dAtA[i] = 0x28
	}
	if m.ActualValue != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ActualValue))
		i--
		dAtA[i] = 0x20
	}
	if m.TargetValue != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.TargetValue))
		i--
		dAtA[i] = 0x18
	}
	if m.Rule != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Rule))
		i--
		dAtA[i] = 0x10
	}
	if m.Met {
		i--
		if m.Met {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Info) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	l = len(m.Referrer)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Active {
		n += 2
	}
	if len(m.ActiveRefCounts) > 0 {
		l = 0
		for _, e := range m.ActiveRefCounts {
			l += sovTypes(uint64(e))
		}
		n += 1 + sovTypes(uint64(l)) + l
	}
	if m.StatusDowngradeAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.StatusDowngradeAt)
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.SelfDelegated != nil {
		l = m.SelfDelegated.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.TeamDelegated != nil {
		l = m.TeamDelegated.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ActiveCount != nil {
		l = m.ActiveCount.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *ActiveAggregations) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FirstLine != 0 {
		n += 1 + sovTypes(uint64(m.FirstLine))
	}
	if m.FirstLineBy3 != 0 {
		n += 1 + sovTypes(uint64(m.FirstLineBy3))
	}
	if m.Team0 != 0 {
		n += 1 + sovTypes(uint64(m.Team0))
	}
	if m.Team15 != 0 {
		n += 1 + sovTypes(uint64(m.Team15))
	}
	if m.Team50 != 0 {
		n += 1 + sovTypes(uint64(m.Team50))
	}
	if m.Team100 != 0 {
		n += 1 + sovTypes(uint64(m.Team100))
	}
	if m.Team300 != 0 {
		n += 1 + sovTypes(uint64(m.Team300))
	}
	return n
}

func (m *StatusCheckResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Overall {
		n += 2
	}
	if len(m.Criteria) > 0 {
		for _, e := range m.Criteria {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *StatusCheckResult_Criterion) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Met {
		n += 2
	}
	if m.Rule != 0 {
		n += 1 + sovTypes(uint64(m.Rule))
	}
	if m.TargetValue != 0 {
		n += 1 + sovTypes(uint64(m.TargetValue))
	}
	if m.ActualValue != 0 {
		n += 1 + sovTypes(uint64(m.ActualValue))
	}
	if m.ParameterX != 0 {
		n += 1 + sovTypes(uint64(m.ParameterX))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Info) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Info: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Info: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Referrer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Referrer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		case 7:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTypes
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ActiveRefCounts = append(m.ActiveRefCounts, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTypes
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTypes
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTypes
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.ActiveRefCounts) == 0 {
					m.ActiveRefCounts = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTypes
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ActiveRefCounts = append(m.ActiveRefCounts, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveRefCounts", wireType)
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusDowngradeAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StatusDowngradeAt == nil {
				m.StatusDowngradeAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.StatusDowngradeAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SelfDelegated", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.SelfDelegated = &v
			if err := m.SelfDelegated.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TeamDelegated", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.TeamDelegated = &v
			if err := m.TeamDelegated.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveCount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ActiveCount == nil {
				m.ActiveCount = &ActiveAggregations{}
			}
			if err := m.ActiveCount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ActiveAggregations) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActiveAggregations: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActiveAggregations: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstLine", wireType)
			}
			m.FirstLine = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FirstLine |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstLineBy3", wireType)
			}
			m.FirstLineBy3 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FirstLineBy3 |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Team0", wireType)
			}
			m.Team0 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Team0 |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Team15", wireType)
			}
			m.Team15 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Team15 |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Team50", wireType)
			}
			m.Team50 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Team50 |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Team100", wireType)
			}
			m.Team100 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Team100 |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Team300", wireType)
			}
			m.Team300 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Team300 |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StatusCheckResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StatusCheckResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StatusCheckResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Overall", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Overall = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Criteria", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Criteria = append(m.Criteria, StatusCheckResult_Criterion{})
			if err := m.Criteria[len(m.Criteria)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StatusCheckResult_Criterion) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Criterion: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Criterion: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Met", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Met = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rule", wireType)
			}
			m.Rule = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Rule |= StatusCheckResult_Criterion_Rule(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetValue", wireType)
			}
			m.TargetValue = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetValue |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActualValue", wireType)
			}
			m.ActualValue = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActualValue |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParameterX", wireType)
			}
			m.ParameterX = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ParameterX |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
