modules:
  - name: runtime
    config:
      "@type": cosmos.app.runtime.v1alpha1.Module
      app_name: AxmApp
      pre_blockers: [ upgrade ]
      # During begin block slashing happens after distr.BeginBlocker so that
      # there is nothing left over in the validator fee pool, so as to keep the CanWithdrawInvariant invariant.
      # NOTE: staking module is required if HistoricalEntries param > 0
      begin_blockers: [ upgrade, distribution, slashing, staking, referral, vote ]
      end_blockers: [ staking ]
      # NOTE: The genutils module must occur after staking so that pools are properly initialized with tokens from genesis accounts.
      # NOTE: The genutils module must also occur after auth so that it can access the params from auth.
      init_genesis: [ auth, bank, distribution, referral, staking, slashing, vote, genutil, upgrade ]
      override_store_keys:
        - module_name: auth
          kv_store_key: acc
  - name: auth
    config:
      "@type": cosmos.auth.module.v1.Module
      bech32_prefix: axm
      module_account_permissions:
        - account: fee_collector
        - account: distribution
          permissions: [ minter, burner ]
        - account: bonded_tokens_pool
          permissions: [ burner, staking ]
        - account: not_bonded_tokens_pool
          permissions: [ burner, staking ]
        - account: referral
          permissions: [ burner ]
        - account: vote
      authority: vote
  - name: bank
    config:
      "@type": cosmos.bank.module.v1.Module
      blocked_module_accounts_override:
        [ auth, distribution, bonded_tokens_pool, not_bonded_tokens_pool ]
      authority: vote
  - name: staking
    config:
      "@type": axiome.staking.module.v1.Module
      authority: vote
  - name: upgrade
    config:
      "@type": cosmos.upgrade.module.v1.Module
      authority: vote
  - name: distribution
    config:
      "@type": axiome.distribution.module.v1.Module
      authority: vote
  - name: slashing
    config:
      "@type": axiome.slashing.module.v1.Module
      authority: vote
  - name: referral
    config:
      "@type": axiome.referral.module.v1.Module
      authority: vote
  - name: vote
    config:
      "@type": axiome.vote.module.v1.Module
      authority: vote
  - name: consensus
    config:
      "@type": cosmos.consensus.module.v1.Module
      authority: vote
  - name: genutil
    config:
      "@type": axiome.genutil.module.v1.Module
  - name: tx
    config:
      "@type": cosmos.tx.config.v1.Config
