// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: axiome/vote/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState - all vote state that must be provided at genesis
type GenesisState struct {
	Government      []string                `protobuf:"bytes,1,rep,name=government,proto3" json:"government" yaml:"government"`
	Params          Params                  `protobuf:"bytes,2,opt,name=params,proto3" json:"params" yaml:"params"`
	CurrentProposal Proposal                `protobuf:"bytes,3,opt,name=current_proposal,json=currentProposal,proto3" json:"current_proposal,omitempty" yaml:"current_proposal,omitempty"`
	StartBlock      int64                   `protobuf:"varint,4,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty" yaml:"start_block,omitempty"`
	Agreed          []string                `protobuf:"bytes,5,rep,name=agreed,proto3" json:"agreed,omitempty" yaml:"agreed,omitempty"`
	Disagreed       []string                `protobuf:"bytes,6,rep,name=disagreed,proto3" json:"disagreed,omitempty" yaml:"disagreed,omitempty"`
	History         []ProposalHistoryRecord `protobuf:"bytes,7,rep,name=history,proto3" json:"history,omitempty" yaml:"history,omitempty"`
	CurrentPoll     *Poll                   `protobuf:"bytes,8,opt,name=current_poll,json=currentPoll,proto3" json:"current_poll,omitempty" yaml:"current_poll,omitempty"`
	PollAnswers     []PollAnswer            `protobuf:"bytes,9,rep,name=poll_answers,json=pollAnswers,proto3" json:"poll_answers,omitempty" yaml:"poll_answers,omitempty`
	PollHistory     []PollHistoryItem       `protobuf:"bytes,10,rep,name=poll_history,json=pollHistory,proto3" json:"poll_history,omitempty" yaml:"poll_history,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_679ef755dc063d96, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetGovernment() []string {
	if m != nil {
		return m.Government
	}
	return nil
}

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetCurrentProposal() Proposal {
	if m != nil {
		return m.CurrentProposal
	}
	return Proposal{}
}

func (m *GenesisState) GetStartBlock() int64 {
	if m != nil {
		return m.StartBlock
	}
	return 0
}

func (m *GenesisState) GetAgreed() []string {
	if m != nil {
		return m.Agreed
	}
	return nil
}

func (m *GenesisState) GetDisagreed() []string {
	if m != nil {
		return m.Disagreed
	}
	return nil
}

func (m *GenesisState) GetHistory() []ProposalHistoryRecord {
	if m != nil {
		return m.History
	}
	return nil
}

func (m *GenesisState) GetCurrentPoll() *Poll {
	if m != nil {
		return m.CurrentPoll
	}
	return nil
}

func (m *GenesisState) GetPollAnswers() []PollAnswer {
	if m != nil {
		return m.PollAnswers
	}
	return nil
}

func (m *GenesisState) GetPollHistory() []PollHistoryItem {
	if m != nil {
		return m.PollHistory
	}
	return nil
}

type PollAnswer struct {
	Acc string `protobuf:"bytes,1,opt,name=acc,proto3" json:"acc" yaml:"acc"`
	Ans bool   `protobuf:"varint,2,opt,name=ans,proto3" json:"ans" yaml:"ans"`
}

func (m *PollAnswer) Reset()         { *m = PollAnswer{} }
func (m *PollAnswer) String() string { return proto.CompactTextString(m) }
func (*PollAnswer) ProtoMessage()    {}
func (*PollAnswer) Descriptor() ([]byte, []int) {
	return fileDescriptor_679ef755dc063d96, []int{1}
}
func (m *PollAnswer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PollAnswer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PollAnswer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PollAnswer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollAnswer.Merge(m, src)
}
func (m *PollAnswer) XXX_Size() int {
	return m.Size()
}
func (m *PollAnswer) XXX_DiscardUnknown() {
	xxx_messageInfo_PollAnswer.DiscardUnknown(m)
}

var xxx_messageInfo_PollAnswer proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GenesisState)(nil), "axiome.vote.v1beta1.GenesisState")
	proto.RegisterType((*PollAnswer)(nil), "axiome.vote.v1beta1.PollAnswer")
}

func init() { proto.RegisterFile("axiome/vote/v1beta1/genesis.proto", fileDescriptor_679ef755dc063d96) }

var fileDescriptor_679ef755dc063d96 = []byte{
	// 649 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x41, 0x6f, 0xd3, 0x3e,
	0x1c, 0x6d, 0xfe, 0xfd, 0xd3, 0xb5, 0xee, 0x10, 0x5b, 0xc6, 0x46, 0x28, 0xac, 0xee, 0x0c, 0x12,
	0x15, 0xb0, 0x46, 0x1b, 0xda, 0x81, 0x1d, 0x40, 0x04, 0xa1, 0xc1, 0x0d, 0x65, 0x9c, 0x76, 0x99,
	0xdc, 0xd4, 0xea, 0x2a, 0x92, 0x38, 0xb2, 0xbd, 0xb1, 0x0a, 0x71, 0xe1, 0xb4, 0x23, 0x7c, 0x83,
	0x7d, 0x17, 0x2e, 0x3b, 0xee, 0xc8, 0xc9, 0x42, 0xdb, 0x05, 0xe5, 0xd8, 0x4f, 0x80, 0x62, 0xbb,
	0x6b, 0x3a, 0x52, 0x6e, 0xc9, 0xef, 0x3d, 0xbf, 0xf7, 0xec, 0x67, 0x19, 0xac, 0xe1, 0xe3, 0x01,
	0x8d, 0x88, 0x7b, 0x44, 0x05, 0x71, 0x8f, 0x36, 0xba, 0x44, 0xe0, 0x0d, 0xb7, 0x4f, 0x62, 0xc2,
	0x07, 0xbc, 0x93, 0x30, 0x2a, 0xa8, 0xbd, 0xa4, 0x29, 0x9d, 0x8c, 0xd2, 0x31, 0x94, 0xc6, 0xed,
	0x3e, 0xed, 0x53, 0x85, 0xbb, 0xd9, 0x97, 0xa6, 0x36, 0x5a, 0x45, 0x6a, 0x09, 0x66, 0x38, 0x32,
	0x62, 0x0d, 0x58, 0xc4, 0x10, 0xc3, 0x84, 0x18, 0x02, 0xfa, 0x51, 0x05, 0xf3, 0x3b, 0xda, 0x7f,
	0x57, 0x60, 0x41, 0xec, 0xd7, 0x00, 0xf4, 0xe9, 0x11, 0x61, 0x71, 0x44, 0x62, 0xe1, 0x58, 0xad,
	0x72, 0xbb, 0xe6, 0x3d, 0x48, 0x25, 0xcc, 0x4d, 0x47, 0x12, 0x2e, 0x0e, 0x71, 0x14, 0x6e, 0xa3,
	0xc9, 0x0c, 0xf9, 0x39, 0x82, 0xfd, 0x01, 0x54, 0x74, 0x0c, 0xe7, 0xbf, 0x96, 0xd5, 0xae, 0x6f,
	0xde, 0xeb, 0x14, 0x6c, 0xaa, 0xf3, 0x5e, 0x51, 0x3c, 0x78, 0x26, 0x61, 0x29, 0x95, 0xd0, 0x2c,
	0x19, 0x49, 0x78, 0x53, 0xab, 0xeb, 0x7f, 0xe4, 0x1b, 0xc0, 0xfe, 0x6e, 0x81, 0x85, 0xe0, 0x90,
	0x31, 0x12, 0x8b, 0xfd, 0x84, 0xd1, 0x84, 0x72, 0x1c, 0x3a, 0x65, 0x65, 0xb0, 0x5a, 0x6c, 0x60,
	0x48, 0xde, 0x8e, 0xb1, 0x68, 0x5c, 0x5f, 0xfe, 0x94, 0x46, 0x03, 0x41, 0xa2, 0x44, 0x0c, 0x47,
	0x12, 0xae, 0x69, 0xdb, 0xd9, 0x1c, 0xe4, 0xdf, 0x32, 0xe0, 0x58, 0xd9, 0xde, 0x03, 0x75, 0x2e,
	0x30, 0x13, 0xfb, 0xdd, 0x90, 0x06, 0x1f, 0x9d, 0xff, 0x5b, 0x56, 0xbb, 0xec, 0x3d, 0x4f, 0x25,
	0x5c, 0xce, 0x8d, 0xa7, 0x5c, 0xee, 0x6b, 0x97, 0x42, 0x18, 0xf9, 0x40, 0xcd, 0xbd, 0x6c, 0x6c,
	0xef, 0x80, 0x0a, 0xee, 0x33, 0x42, 0x7a, 0xce, 0x0d, 0x55, 0x83, 0x9b, 0x4a, 0xb8, 0xa0, 0x27,
	0x53, 0x8a, 0x77, 0xb4, 0xe2, 0x75, 0x04, 0xf9, 0x66, 0xb9, 0xbd, 0x0b, 0x6a, 0xbd, 0x01, 0x37,
	0x5a, 0x15, 0xa5, 0xb5, 0x95, 0x4a, 0xb8, 0x74, 0x35, 0x9c, 0x92, 0x6b, 0x68, 0xb9, 0x02, 0x10,
	0xf9, 0x13, 0x1d, 0xfb, 0x33, 0x98, 0x3b, 0x18, 0x70, 0x41, 0xd9, 0xd0, 0x99, 0x6b, 0x95, 0xdb,
	0xf5, 0xcd, 0xc7, 0xff, 0xec, 0xe0, 0xad, 0xe6, 0xfa, 0x24, 0xa0, 0xac, 0xe7, 0x6d, 0x99, 0x42,
	0x16, 0x8d, 0xc4, 0x54, 0x00, 0x47, 0x07, 0xf8, 0x0b, 0x42, 0xfe, 0xd8, 0xd1, 0xfe, 0x02, 0xe6,
	0xaf, 0x6a, 0xa2, 0x61, 0xe8, 0x54, 0xd5, 0x2d, 0xb8, 0x5b, 0x9c, 0x80, 0x86, 0xa1, 0xf7, 0xf2,
	0x4c, 0x42, 0x2b, 0x95, 0x70, 0x25, 0xbf, 0x6c, 0xca, 0x75, 0xf5, 0x5a, 0xfb, 0x53, 0x38, 0xf2,
	0xeb, 0xe3, 0xe6, 0x69, 0x18, 0xda, 0x5f, 0x2d, 0x30, 0x9f, 0x11, 0xf6, 0x71, 0xcc, 0x3f, 0x11,
	0xc6, 0x9d, 0x9a, 0x3a, 0x01, 0x38, 0xd3, 0xff, 0x95, 0xe2, 0x79, 0x2f, 0xcc, 0xb6, 0x57, 0xf2,
	0x8b, 0x8b, 0x6e, 0x47, 0x31, 0xee, 0xd7, 0x93, 0x2b, 0x2d, 0x6e, 0x9f, 0x8c, 0x43, 0x8c, 0x6b,
	0x00, 0x2a, 0xc4, 0xc3, 0x99, 0x21, 0x4c, 0x05, 0xef, 0x04, 0x89, 0xd4, 0x79, 0x4c, 0x92, 0x14,
	0xb5, 0xb0, 0x9a, 0x4b, 0x52, 0x50, 0x85, 0x8a, 0x62, 0x14, 0xd1, 0x01, 0x00, 0x93, 0x5d, 0xda,
	0x8f, 0x40, 0x19, 0x07, 0x81, 0x63, 0xb5, 0xac, 0x76, 0xcd, 0x5b, 0x4e, 0x25, 0xcc, 0x7e, 0x47,
	0x12, 0x02, 0x73, 0x4f, 0x83, 0x00, 0xf9, 0xd9, 0x48, 0x11, 0x63, 0xfd, 0x46, 0x54, 0x0d, 0x31,
	0xe6, 0x39, 0x62, 0xcc, 0x33, 0x62, 0xcc, 0xb7, 0xab, 0x27, 0xa7, 0xb0, 0xf4, 0xfb, 0x14, 0x96,
	0xbc, 0x37, 0x67, 0x17, 0x4d, 0xeb, 0xfc, 0xa2, 0x69, 0xfd, 0xba, 0x68, 0x5a, 0xdf, 0x2e, 0x9b,
	0xa5, 0xf3, 0xcb, 0x66, 0xe9, 0xe7, 0x65, 0xb3, 0xb4, 0xf7, 0xa4, 0x3f, 0x10, 0x07, 0x87, 0xdd,
	0x4e, 0x40, 0x23, 0x57, 0x9f, 0xc0, 0x7a, 0xc2, 0xa8, 0x8b, 0x8f, 0xa3, 0xf5, 0x98, 0xf6, 0x88,
	0x7b, 0xac, 0x1f, 0x41, 0xf5, 0xf8, 0x75, 0x2b, 0xea, 0xf5, 0x7b, 0xf6, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x46, 0x5b, 0xa7, 0xdb, 0x90, 0x05, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PollHistory) > 0 {
		for iNdEx := len(m.PollHistory) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PollHistory[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.PollAnswers) > 0 {
		for iNdEx := len(m.PollAnswers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PollAnswers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if m.CurrentPoll != nil {
		{
			size, err := m.CurrentPoll.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if len(m.History) > 0 {
		for iNdEx := len(m.History) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.History[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Disagreed) > 0 {
		for iNdEx := len(m.Disagreed) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Disagreed[iNdEx])
			copy(dAtA[i:], m.Disagreed[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.Disagreed[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Agreed) > 0 {
		for iNdEx := len(m.Agreed) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Agreed[iNdEx])
			copy(dAtA[i:], m.Agreed[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.Agreed[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.StartBlock != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.StartBlock))
		i--
		dAtA[i] = 0x20
	}
	{
		size, err := m.CurrentProposal.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Government) > 0 {
		for iNdEx := len(m.Government) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Government[iNdEx])
			copy(dAtA[i:], m.Government[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.Government[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *PollAnswer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PollAnswer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PollAnswer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Ans {
		i--
		if m.Ans {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Acc) > 0 {
		i -= len(m.Acc)
		copy(dAtA[i:], m.Acc)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Acc)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Government) > 0 {
		for _, s := range m.Government {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.CurrentProposal.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.StartBlock != 0 {
		n += 1 + sovGenesis(uint64(m.StartBlock))
	}
	if len(m.Agreed) > 0 {
		for _, s := range m.Agreed {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Disagreed) > 0 {
		for _, s := range m.Disagreed {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.History) > 0 {
		for _, e := range m.History {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.CurrentPoll != nil {
		l = m.CurrentPoll.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.PollAnswers) > 0 {
		for _, e := range m.PollAnswers {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PollHistory) > 0 {
		for _, e := range m.PollHistory {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *PollAnswer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Acc)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Ans {
		n += 2
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Government", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Government = append(m.Government, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentProposal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CurrentProposal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartBlock", wireType)
			}
			m.StartBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Agreed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Agreed = append(m.Agreed, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Disagreed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Disagreed = append(m.Disagreed, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field History", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.History = append(m.History, ProposalHistoryRecord{})
			if err := m.History[len(m.History)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentPoll", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CurrentPoll == nil {
				m.CurrentPoll = &Poll{}
			}
			if err := m.CurrentPoll.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PollAnswers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PollAnswers = append(m.PollAnswers, PollAnswer{})
			if err := m.PollAnswers[len(m.PollAnswers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PollHistory", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PollHistory = append(m.PollHistory, PollHistoryItem{})
			if err := m.PollHistory[len(m.PollHistory)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PollAnswer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PollAnswer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PollAnswer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Acc", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Acc = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ans", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Ans = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
